fra + frp
apertium/apertium-html-tools pull request #382
Opened 2020-09-09 06:23 UTC by hectoralos

Added the missing strings in fra.json and the new frp language (Arpitan/Francoprovençal).

2020-09-09 23:20 UTC, sushain97 requested changes
This is great! Just one thing that I think you accidentally changed.

2020-09-09 23:20 UTC, sushain97 commented on assets/strings/README.md
> -After editing localizations, please run `make` and commit its changes.
Could you undo this change?

2020-09-10 04:39 UTC, hectoralos commented
Hopefully I've done it correctly. It seems that I didn't pull the last version before introducing the changes in the file.

2020-09-11 04:19 UTC, sushain97 commented
I think your new changes overwrote the wrong file: https://github.com/apertium/apertium-html-tools/pull/382/files

2020-09-11 06:13 UTC, hectoralos commented
I close this request I begin another from the scratch.

2020-09-11 06:13 UTC, closed without merging