Added Hindi and Santali language Translations
apertium/apertium-html-tools pull request #425
Opened 2021-12-24 18:01 UTC by Prasanta-Hembram

2022-01-04 06:55 UTC, sushain97 requested changes
@Prasanta-Hembram Thanks for the PR! Please update `locales.json` and then run `make` in `src/strings`. Please update the PR afterwards and I'd be happy to merge.

Apologies for the review delay.

2022-01-04 11:26 UTC, Prasanta-Hembram commented
I too was busy for this new year eve no issue :-) . Thanks @sushain97 for suggesting me to make change, i hope that i have done everything good :-). Also, i want to know how to test those translations. Followed this guide https://wiki.apertium.org/wiki/Apertium-html-tools but unable to test my translations. Index file present is the src folder is not working.

2022-01-04 11:28 UTC, Prasanta-Hembram reviewed
done

2022-01-05 06:25 UTC, sushain97 commented
> Also, i want to know how to test those translations. Followed this guide https://wiki.apertium.org/wiki/Apertium-html-tools but unable to test my translations. Index file present is the src folder is not working.

The instructions are here: https://github.com/apertium/apertium-html-tools#contributing

2022-01-05 13:09 UTC, Prasanta-Hembram commented
Thanks for the help @sushain97 i encountered some error here, i have successfully installed Node.js and Yarn but after giving  yarn install --dev command i get error which i'm not able to fix. Error is as follows, for which built is not successful. Just want to view the site in html for newly added language, any shortcut ?? or in order to fix what further steps are needed (detailed beginner guide is recommended :-)) 

yarn install --dev
yarn install v1.22.17
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[-----------------------------------------------------------------------] 1/757Segmentation fault

2022-01-06 06:02 UTC, sushain97 commented
> Problem No.1) I have successfully installed Node.js and Yarn but after giving yarn install --dev command i get error which I'm not able to fix. Error is as follows below, for which built is not successful for me. Just want to view the site in html for newly added language, any shortcut ?? or in order to fix what further steps are needed (detailed beginner guide is recommended :-))

Hm, I have a suspicion that you're using Yarn v2 instead of Yarn v1.

You could try these instructions instead: https://github.com/apertium/apertium-html-tools#building.

Combine the `docker` build with `yarn serve` or just directly accessing the built `index.eng.html`.

2022-01-06 15:46 UTC, Prasanta-Hembram commented
Thanks @sushain97 for the help i have set Yarn v1 and the build is successfull. I have also updated my translations, and everything is ready now. I hope i have commited well !!

2022-01-06 15:52 UTC, Prasanta-Hembram commented
Also, how to translate these languages
![Screenshot 2022-01-06 204452](https://user-images.githubusercontent.com/51163799/148409977-02cb1fac-966a-4ae3-8abf-1bd00a2a2810.png)
I found https://github.com/apertium/apertium-apy/tree/master/language_names but still confused where to add these language translations. May be most probably in "manual-additions.tsv"?? For Santali language should i create a new tsv file or add it to there too.

2022-01-06 17:45 UTC, sushain97 requested changes
This PR should also not have any changes to `yarn.lock`.

2022-01-06 17:45 UTC, sushain97 commented on .yarnrc
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Please don't add this or the `.yarn` changes :)

2022-01-06 17:45 UTC, sushain97 commented on .yarnrc
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
(or `package-json.lock`)

2022-01-06 17:45 UTC, sushain97 commented on src/strings/ara.json
> +        "completion": " 97%  90.09%",
Could you back out the trivial changes to these files?

2022-01-06 17:45 UTC, sushain97 commented
> Also, how to translate these languages ![Screenshot 2022-01-06 204452](https://user-images.githubusercontent.com/51163799/148409977-02cb1fac-966a-4ae3-8abf-1bd00a2a2810.png) I found https://github.com/apertium/apertium-apy/tree/master/language_names but still confused where to add these language translations. May be most probably in "manual-additions.tsv"?? For Santali language should i create a new tsv file or add it to there too.

Here are the directions: tree/master/language_names#manual---edit

2022-01-06 18:36 UTC, Prasanta-Hembram commented
Again, Thanks @sushain97 i will also update those language in apy repo. I will try to correct my error anyhow. I hope i have deleted correct files.

2022-01-06 18:46 UTC, Prasanta-Hembram commented
> > Also, how to translate these languages ![Screenshot 2022-01-06 204452](https://user-images.githubusercontent.com/51163799/148409977-02cb1fac-966a-4ae3-8abf-1bd00a2a2810.png) I found https://github.com/apertium/apertium-apy/tree/master/language_names but still confused where to add these language translations. May be most probably in "manual-additions.tsv"?? For Santali language should i create a new tsv file or add it to there too.
> 
> Here are the directions: https://github.com/apertium/apertium-apy/tree/master/language_names#manual---edit

Manual - EDIT

    **manual-fixes.tsv** contains fixes to the scraped data.
    **manual-additions.tsv** contains additions to the scraped data.
    variants.tsv contains fixes/additions to the scraped data for language variants.
    turkic.tsv contains Turkic language names.

N.B. Due to historical reasons, there are currently some additions in manual-fixes.tsv.

So, HIndi  language locale translation should go to **manual-fixes.tsv** and Santali language locale translations (new language in apy) should be in **manual-additions.tsv** or both should be in which files if I'm wrong??

2022-01-07 04:15 UTC, sushain97 commented
> So, HIndi language locale translation should go to **manual-fixes.tsv** and Santali language locale translations (new language in apy) should be in **manual-additions.tsv** or both should be in which files if I'm wrong??

Updates to existing language names should go in `fixes` and new one should go in `additions`.

2022-01-07 04:15 UTC, sushain97 commented on .yarnrc
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
This file should be deleted as well as the changes to `yarn.lock` and `package.json`.

2022-01-07 04:34 UTC, Prasanta-Hembram commented
HI, @sushain97 can you check again i have made some changes.

2022-01-07 04:35 UTC, sushain97 commented
Could you revert the changes to `package.json` and `yarn.lock`?

2022-01-07 04:48 UTC, Prasanta-Hembram commented
> `package.json` and `yarn.lock`?

can you again check?

2022-01-07 05:48 UTC, sushain97 approved these changes

2022-01-07 05:48 UTC, merged