Create skr.json
apertium/apertium-html-tools pull request #459
Opened 2023-03-02 16:00 UTC by mpQadir

Add Saraiki language

2023-03-02 17:55 UTC, sushain97 requested changes
Thanks! Let's add skr to https://github.com/apertium/apertium-html-tools/blob/master/src/strings/locales.json and add the changes of running `make` in https://github.com/apertium/apertium-html-tools/tree/master/src/strings.

2023-03-02 17:55 UTC, sushain97 commented on src/strings/skr.json
> +            "sushain97"
update this?

2023-03-02 17:55 UTC, sushain97 commented on src/strings/skr.json
> +            "skr"
let's remove the duplicate here?

2023-03-03 02:34 UTC, mpQadir commented
Please, fix, remove duplicate and merge.

On Thu, Mar 2, 2023, 10:55 PM Sushain Cherivirala ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks! Let's add skr to
> https://github.com/apertium/apertium-html-tools/blob/master/src/strings/locales.json
> and add the changes of running make in
> https://github.com/apertium/apertium-html-tools/tree/master/src/strings.
> ------------------------------
>
> In src/strings/skr.json
> <https://github.com/apertium/apertium-html-tools/pull/459#discussion_r1123512120>
> :
>
> > @@ -0,0 +1,67 @@
> +{
> +    ***@***.***": {
> +        "authors": [
> +            "sushain97"
>
> update this?
> ------------------------------
>
> In src/strings/skr.json
> <https://github.com/apertium/apertium-html-tools/pull/459#discussion_r1123512265>
> :
>
> > @@ -0,0 +1,67 @@
> +{
> +    ***@***.***": {
> +        "authors": [
> +            "sushain97"
> +        ],
> +        "last-updated": "2023-03-02",
> +        "locale": [
> +            "skr",
> +            "skr"
>
> let's remove the duplicate here?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apertium/apertium-html-tools/pull/459#pullrequestreview-1322342850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXPYAW4B25OPXC3ZB6TKOP3W2DNI5ANCNFSM6AAAAAAVNSB4EA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-23 05:23 UTC, sushain97 commented
@mpQadir is there someone in the community that can vouch for these translations? I unfortunately cannot properly review them.

2023-03-23 05:24 UTC, sushain97 commented
https://github.com/apertium/apertium-html-tools/pull/460 should be combined into this PR.

2023-03-23 07:23 UTC, mpQadir reviewed
This be done.  It is Ok.

2023-03-23 12:25 UTC, meesumalam commented
> > @mpQadir is there someone in the community that can vouch for these translations? I unfortunately cannot properly review them.
> 
> @meesumalam could you take a look at these?

Yes, I can.

2023-05-12 15:13 UTC, mpQadir commented
> @SaudQadir may verify these.



> > > @mpQadir is there someone in the community that can vouch for these translations? I unfortunately cannot properly review them.
> > 
> > 
> > @meesumalam could you take a look at these?
> 
> Yes, I can.

2023-05-12 17:14 UTC, SaudQadir commented
> > @SaudQadir may verify these.
> 
> > > > @mpQadir is there someone in the community that can vouch for these translations? I unfortunately cannot properly review them.
> > > 
> > > 
> > > @meesumalam could you take a look at these?
> > 
> > 
> > Yes, I can.

I am Saraiki native, and I verify that the above translation is correct. and recommended for merge, please.

2023-05-13 03:50 UTC, sushain97 approved these changes

2023-05-13 05:47 UTC, merged