issue#462 about section
apertium/apertium-html-tools pull request #467
Opened 2023-03-12 15:42 UTC by hazemk537

2023-03-12 18:13 UTC, sushain97 requested changes
This looks reasonable but it's not clear to me why you've added both a PNG and an SVG version. The SVG is preferable since it's significantly smaller.

2023-03-12 18:37 UTC, hazemk537 commented
Because , I found an error while building when I used the SVG version , so I convert it to PNG

2023-03-12 18:43 UTC, sushain97 commented
If you run into an unexpected issue, please ask for help with it rather than reverting to a sub-optimal choice. In this case, you'll need to modify Jest config, ESBuild config and TS declarations to allow for SVG files.

2023-03-12 18:44 UTC, hazemk537 commented
okay , I can do that

2023-03-12 19:49 UTC, hazemk537 commented
should i install esbuild-plugin-svg and use it ?
it is deprecated

2023-03-12 19:57 UTC, sushain97 commented
Please do not add any new config files or new dependencies. The existing support for gif/png files should extend to svg files immediately.

2023-03-14 08:51 UTC, hazemk537 commented
# After many tries 
- I cannot see the svg file in the dist folder .
- I searched and found that 
1. The esbuild built-in loader support s GIF  , PNG  and JPEG and donot support SVG.
2.  but  If you want to load SVG files ,You should use extension like esbuild-plugin-svg

# References
[If you want to load PNG, JPEG or GIF files as data URLs in your JavaScript code, you can use esbuild’s built-in loader option](https://blog.logrocket.com/getting-started-esbuild/)

[If you want to load SVG files as strings or custom elements in your JavaScript code, you can use esbuild-plugin-svg](https://github.com/nativew/esbuild-plugin-svg)

2023-03-14 09:45 UTC, TinoDidriksen commented
We do NOT want any of the images as data URLs. But surely it can't be true that we need something special to copy an asset from the source to the build folder and insert the relative path to it.

2023-03-14 09:56 UTC, hazemk537 commented
okay , should I repo the repo to PNG version ? to accept the pull request ?

2023-03-14 11:08 UTC, TinoDidriksen commented
No, the SVG version is correct. It should simply be handled same as the other images are - which is, copied to the build folder and linked from there.

2023-03-14 12:02 UTC, hazemk537 commented
No need to copy to dist , its working now using the SVG !!
![image](https://user-images.githubusercontent.com/63047860/224995048-57eace2b-c7c0-4aac-aaa8-fef4037a5478.png)

2023-03-15 06:22 UTC, sushain97 requested changes

2023-03-15 06:22 UTC, sushain97 commented on src/components/footer/img/GSOC_logo.png
Can this file be deleted now?

2023-03-15 06:22 UTC, sushain97 commented on src/globals.d.ts
> +}
Please add back the trailing newline.

2023-03-15 10:10 UTC, hazemk537 commented
Done

2023-03-18 04:00 UTC, sushain97 commented
Please fix the build failures.

2023-03-18 05:19 UTC, hazemk537 commented
done

2023-03-19 01:38 UTC, sushain97 commented
I don't think we should be increasing the test timeout. It's probably just flaky? Another run will fix it.

2023-03-19 06:53 UTC, hazemk537 commented
I tried runnibg it using jest and without increasing the timeout ,one file sometimes fails but after the increasing , no fails .
I think we shoud increase it for future non fake  issues during build .
do you agrre with me ?

2023-03-19 07:28 UTC, sushain97 commented
No, we should fix the test to not flake instead.

2023-03-19 07:58 UTC, hazemk537 commented
so the problem is inside the test file itself ! I got it

2023-03-20 05:26 UTC, sushain97 approved these changes

2023-03-20 05:26 UTC, merged