fixes #477 (Build should not rely on git)
apertium/apertium-html-tools pull request #481
Opened 2023-12-08 10:16 UTC by satti-hari-krishna-reddy

**Description :**

This pull request addresses the issue where the build process was relying on Git for version information. The problem arose when the build process did not have Git available.

**Changes Made :**

  -In package.json, added a new script command for the build that sets the BUILD_VERSION environment variable before 
   running the build script.

 -In build.ts, modified the code to use the process.env.BUILD_VERSION. If BUILD_VERSION is not provided, it will fall back to the version specified in package.json.

2023-12-08 10:30 UTC, satti-hari-krishna-reddy commented
@sushain97 could you please review my changes? Your feedback would be highly appreciated.

2023-12-11 01:29 UTC, sushain97 requested changes
Seems reasonable

2023-12-11 01:29 UTC, sushain97 commented on package.json
>    "license": "GPL-3.0-or-later",
Can you update the `version` field above to actually match the latest released GH version if we're going to use it as the canonical source?

2023-12-12 15:56 UTC, satti-hari-krishna-reddy commented
@sushain97 sorry for late reply college work has been busy, Sure, I'll update the version in package.json field above to actually match the latest released git hub version but i got a doubt , Since we're moving away from direct reliance on Git ,will manual updates to package.json be required for every  release?

2023-12-12 16:43 UTC, TinoDidriksen commented
> ...will manual updates to package.json be required for every release?

Yes. That is the point. It's about what the source of truth is, and I hold that it should be the code - GitHub is merely storage, and must not be an integral part of the project.

2023-12-12 22:16 UTC, sushain97 commented
> Since we're moving away from direct reliance on Git ,will manual updates to package.json be required for every release?

Yes, this is fine. Ideally, we set up a GH workflow to create a tag and it'll fail when the tag already exists and succeed when a commit is pushed to `master` with a new tag.

2023-12-12 22:17 UTC, sushain97 commented
> Yes. That is the point. It's about what the source of truth is, and I hold that it should be the code - GitHub is merely storage, and must not be an integral part of the project.

I don't disagree with this but I'd argue GitHub isn't relevant here. The tags are a Git construct which is arguably part of the source of truth. The point that a build shouldn't require `.git` is one I agree with though so this is fine in general.

2023-12-14 11:59 UTC, satti-hari-krishna-reddy commented
Hey @sushain97 , @TinoDidriksen , I've made some changes to the code. Can you take a look and let me know if everything's good now? Thanks!

2023-12-14 17:56 UTC, sushain97 submitted a review, later dismissed

2023-12-14 17:59 UTC, sushain97 commented
@satti-hari-krishna-reddy CI is failing.

2023-12-15 02:06 UTC, satti-hari-krishna-reddy commented
@sushain97 , I've got the Prettier error fixed, so the CI should be good to go now!

2023-12-17 06:10 UTC, sushain97 approved these changes

2023-12-17 06:12 UTC, merged