Fix: Ensure Footer Visibility on Smaller Screens
apertium/apertium-html-tools pull request #489
Opened 2024-02-25 11:25 UTC by thrishank

### Summary
#468 Issue
This pull request addresses an issue where the footer was not rendering on smaller screens due to the d-none class. The visibility of the footer is crucial for providing a seamless user experience across different devices.

### Changes Made
- Removed the d-none class from the div in the footer folder index file, enabling the footer to be visible on smaller screens.

### Why
The d-none class was unintentionally hiding the footer on smaller screens, affecting the overall user experience. This change ensures consistent visibility across all screen sizes. The d-none class in Bootstrap is a utility class that sets an element to display: none! important;, effectively hiding it.

### ScreenShots
**before**
![Screenshot 2024-02-25 163600](https://github.com/apertium/apertium-html-tools/assets/86158204/1d59046e-2041-436d-9986-f10baf35dce9)
**After**
![Screenshot 2024-02-25 163441](https://github.com/apertium/apertium-html-tools/assets/86158204/e115ded4-47ce-428e-b7fc-702ad2125242)

- Tested on various devices and screen sizes.
-  Ensured the removal of the d-none class did not introduce any unintended side effects.

This PR is ready for review. Your feedback is appreciated!

2024-02-25 18:51 UTC, sushain97 requested changes
Unfortunately, this is exceptionally noisy UI for a mobile screen and displays redundant content ("Spotted a mistake..." appears twice).

2024-02-25 19:54 UTC, thrishank commented
Hey @sushain97 thanks for the feedback.  I have removed the redundant content.
![image](https://github.com/apertium/apertium-html-tools/assets/86158204/c9483125-c778-4a01-956c-feb134a56535)
Should  I work on a clean UI ?

2024-02-25 19:55 UTC, sushain97 commented
That would be necessary to have this merged.

2024-02-27 04:20 UTC, sushain97 commented
This is still far too much vertical space. Try looking at how other websites handle collapsing a footer on mobile viewports?

2024-02-27 16:23 UTC, thrishank commented
https://github.com/apertium/apertium-html-tools/assets/86158204/45f451d7-6b92-4b27-9262-303be0ebb03b
Reduced the vertical space a little bit. 
![image](https://github.com/apertium/apertium-html-tools/assets/86158204/778878ee-f3bf-4257-98ca-f363e74cd8c2)

2024-03-04 11:03 UTC, thrishank commented on src/components/footer/index.tsx
> +                <FontAwesomeIcon icon={faCode} /> {t('github ') + version}
Sorry, removed it. Just thought it would be good to have icon.

2024-03-05 06:35 UTC, sushain97 approved these changes

2024-03-05 18:35 UTC, thrishank commented
In the Footer test suite, the "opens about dialog on desktop" test was failing due to accessing an undefined element at index 1 in the buttons array. Upon investigating I found that there is only one element in the buttons array. The issue was resolved by updating the index to 0, ensuring the test clicks on the correct button.
@sushain97

2024-03-13 15:36 UTC, merged

2024-03-20 16:43 UTC, thrishank commented
Hey @sushain97 I am thinking of participating for apertium GSoC. Who should I contact ? 

Thank You